import { HorizontalBox, Button } from "std-widgets.slint";

export component DialogHeader inherits HorizontalBox {
    in property <string> title: "";
    callback cancel();

    Rectangle {
        preferred-width: 24px;
        min-width: 24px;
    }
    Text {
        text: root.title;
        font-size: 16px;
        font-weight: 700;
        horizontal-alignment: center;
    }
    HorizontalLayout {
        alignment: end;
        Button {
            text: "×";
            clicked => {
                root.cancel();
            }
        }
    }
}

export component DialogSeparator inherits Rectangle {
    height: 1px;
    background: #ccc;
}

export component DialogSpacer inherits Rectangle {
    height: 8px;
}



