import { VerticalBox, ScrollView } from "std-widgets.slint";
import { DialogHeader, DialogSeparator } from "cmp_dialog_header.slint";

export component TocDialog inherits Rectangle {
    width: 500px;
    height: 400px;
    background: #ffffff;
    border-width: 2px;
    border-color: #333;

    in property <string> toc-list-text: "";

    callback cancel();

    TouchArea {
        width: 100%;
        height: 100%;
        clicked => { }
    }
    VerticalBox {
        height: 100%;
        padding: 20px;
        spacing: 0px;

        DialogHeader {
            title: "Table of contents";
            cancel => {
                root.cancel();
            }
        }

        DialogSeparator {}

        ScrollView {
            preferred-height: 100%;
            VerticalBox {
                padding-left: 5px;
                padding-right: 5px;
                padding-top: 5px;
                padding-bottom: 5px;
                Text {
                    text: root.toc-list-text;
                    width: 100%;
                    wrap: word-wrap;
                    color: #333;
                }
            }
        }
    }
}
