import { VerticalBox, ScrollView } from "std-widgets.slint";
import { DialogHeader, DialogSeparator } from "cmp_dialog_header.slint";

export component ShortcutsDialog inherits Rectangle {
    width: 480px;
    height: 420px;
    background: #ffffff;
    border-width: 2px;
    border-color: #333;

    in property <string> shortcuts-list-text: "";

    callback cancel();

    TouchArea {
        width: 100%;
        height: 100%;
        clicked => { }
    }
    VerticalBox {
        height: 100%;
        padding: 20px;
        spacing: 0px;

        DialogHeader {
            title: "Keyboard shortcuts";
            cancel => {
                root.cancel();
            }
        }

        DialogSeparator {}

        ScrollView {
            preferred-height: 100%;
            VerticalBox {
                padding-left: 5px;
                padding-right: 5px;
                padding-top: 5px;
                padding-bottom: 5px;
                Rectangle {
                    vertical-stretch: 1;
                    min-height: 0;
                    clip: true;
                    TextInput {
                        text: root.shortcuts-list-text;
                        width: 100%;
                        height: 100%;
                        wrap: word-wrap;
                        read-only: true;
                    }
                }
            }
        }
    }
}
